spring:
  application:
    name: stm-servicos

  datasource:
#    url: jdbc:mysql://localhost:3306/db_guardian?createDatabaseIfNotExist=true&serverTimezone=UTC
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
#    url: jdbc:h2:file:~/osdb;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE
#    username: sa
#    password: 123
#    driverClassName: org.h2.Driver
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
